language: php

sudo: required

services:
  - docker

php:
  - 7.1

before_script:
  - docker-compose up -d
  - cp app.travis.yml app.yml
  - composer self-update
  - composer install --no-interaction
  - docker run -it arangodb echo 'db._createDatabase("dbname");' |  arangosh --server.username root --server.password YourRootPassword

script:
  - docker exec -it apache vendor/bin/phpunit tests/