# Aplication configuration file

application:
  name: Skeleton
  version: version
  debug: true

api:
  prefix: api
  version: v1
  enabled: false

arangodb:
  database: dbname
  host: arangodb
  port: 8529
  user: root
  password: YourRootPassword
  auth: Basic
  connection: Close
  timeout: 3
  reconnect: true
  create: true
