# v2 syntax
version: '2'

services:
  arangodb:
    container_name: arangodb
    image: arangodb/arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=YourRootPassword
    volumes:
      - ./.docker/arangodb/database:/var/lib/arangodb
      - ./.docker/arangodb/apps:/var/lib/arangodb-apps
    ports:
      - "8529:8529"


  apache:
    container_name: apache
    image: ambientum/php:7.1-apache
    volumes:
      - .:/var/www/app
    ports:
      - "8000:80"
    links:
      - arangodb
